[build]
  command = "npm run build"      # Run your regular build command
  publish = "build"              # Publish folder for a React app (ensure this matches the build output folder)

[[redirects]]
  from = "/*"                    # Redirect all requests to index.html for client-side routing
  to = "/index.html"             # React Router handles client-side routing
  status = 200
  force = true                   # Ensures redirect even for non-existent files