[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  directory = "functions"  # This points to the directory where SSR functions are placed

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"  # Ensure this is correct
  status = 200