[build]
  command = "echo $NITRO_PRESET && npm run build"
  publish = ".output/public"
  environment = { NITRO_PRESET = "netlify" }

[functions]
  directory = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions-internal/server"
  status = 200
