[build]
  command = "npm run build && cp -r .vinxi/build/. .output""
  publish = ".output/public"

[functions]
  directory = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions-internal/server"
  status = 200

# Default environment variables for the build process
[build.environment]
  NITRO_PRESET = "netlify" 

# Production environment-specific settings
[context.production.environment]
  NITRO_PRESET = "netlify"

# Deploy preview-specific settings
[context.deploy-preview.environment]
  NITRO_PRESET = "netlify"

# Branch deploy-specific settings
[context.branch-deploy.environment]
  NITRO_PRESET = "netlify"

# Local environment (Netlify CLI) settings
[context.local.environment]
  NITRO_PRESET = "netlify"
