[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  directory = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions-internal/server"
  status = 200

[build.environment]
  NITRO_PRESET = "netlify"
  

